"""Add user_no field to sys_user table

Revision ID: 9861ec1afbb2
Revises: e04764f64c92
Create Date: 2026-01-21 01:11:49.788741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9861ec1afbb2'
down_revision = 'e04764f64c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_no', sa.String(length=32), nullable=True, comment='学号/工号'))
        batch_op.create_unique_constraint(None, ['user_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_no')

    # ### end Alembic commands ###
