"""Initial migration

Revision ID: e04764f64c92
Revises: 
Create Date: 2026-01-21 00:57:43.542649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04764f64c92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_zone',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=50), nullable=False, comment='区域名称'),
    sa.Column('fee_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='每小时费率'),
    sa.Column('free_time', sa.Integer(), nullable=True, comment='免费时长(分钟)'),
    sa.Column('total_spots', sa.Integer(), nullable=True, comment='总车位数'),
    sa.PrimaryKeyConstraint('zone_id'),
    sa.UniqueConstraint('zone_name')
    )
    op.create_table('sys_user',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='加密密码'),
    sa.Column('role', sa.Integer(), nullable=True, comment='角色'),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True, comment='余额'),
    sa.Column('credit_score', sa.Integer(), nullable=True, comment='信用分'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否冻结'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='注册时间'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('car',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False, comment='车牌号'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.user_id'], ),
    sa.PrimaryKeyConstraint('car_id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_plate_number'), ['plate_number'], unique=True)

    op.create_table('parking_spot',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('spot_no', sa.String(length=20), nullable=False, comment='车位编号(如A-001)'),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True, comment='车位状态'),
    sa.Column('current_plate', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['parking_zone.zone_id'], ),
    sa.PrimaryKeyConstraint('spot_id')
    )
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_spot_status'), ['status'], unique=False)

    op.create_table('parking_order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='业务单号'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False, comment='实际入场车牌'),
    sa.Column('status', sa.Integer(), nullable=True, comment='订单状态'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='预约时间'),
    sa.Column('in_time', sa.DateTime(), nullable=True, comment='入场时间'),
    sa.Column('out_time', sa.DateTime(), nullable=True, comment='出场时间'),
    sa.Column('pay_time', sa.DateTime(), nullable=True, comment='支付时间'),
    sa.Column('total_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='总费用'),
    sa.Column('real_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='实收费用'),
    sa.ForeignKeyConstraint(['spot_id'], ['parking_spot.spot_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    with op.batch_alter_table('parking_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_order_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_parking_order_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_order_status'))
        batch_op.drop_index(batch_op.f('ix_parking_order_order_no'))

    op.drop_table('parking_order')
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_spot_status'))

    op.drop_table('parking_spot')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_plate_number'))

    op.drop_table('car')
    op.drop_table('sys_user')
    op.drop_table('parking_zone')
    # ### end Alembic commands ###
